
[package]
name = "app"
version = "0.1.0"
build = "build.rs"

[dependencies]
sgx_types = { version = "1.1.4", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_urts  = { version = "1.1.4", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
